name: Deploy to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: toiletlabels

jobs:
  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Required for OIDC login
      contents: read  # Explicitly request read access to repo contents
    
    steps:
      - uses: actions/checkout@v4
  
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11' 
  
      - run: python -m pip install --upgrade pip

      - run: pip install -r requirements.txt
  
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'

# Setup instructions:
# 1. Create an Azure Service Principal for GitHub Actions with Contributor role on your Web App resource scope.
# 2. Add the following GitHub repository secrets:
