name: Deploy to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: toiletlabels

jobs:
  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Required for OIDC login
      contents: read  # Explicitly request read access to repo contents
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'

# Setup instructions:
# 1. Create an Azure Service Principal for GitHub Actions with Contributor role on your Web App resource scope.
# 2. Add the following GitHub repository secrets:
